language: go
go:          
  - "1.13.4" 
services:
  - docker  


install:
  - docker build -t neowood/twilight:latest .

script:
  - echo "$DOCKER_PASSWORD"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; docker push neowood/twilight:latest
